version: 1.0
os: windows
files:
  - source: app
    destination: /var/www
  - source: Scripts/webapi.service
    destination: /etc/systemd/system
hooks:
  BeforeInstall:
    - location: Scripts/before-install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: Scripts/application-stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/application-start.sh
      timeout: 300
      runas: root